PROG=	fgdisk
SRCS=	add.c boot.c create.c destroy.c efi.c flag.c gpt.c \
	label.c main.c map.c meatbag.c migrate.c \
	recover.c remove.c rename.c resize.c show.c verify.c
WARNS?=	6
MAN=	fgdisk.8

.include <bsd.prog.mk>
